### ISSUE TITLE
Fix z index issues for banners on graphic violence media

### ISSUE THREAD

**Issue by milesmcc** [atlosdotorg/atlos#311] opened 2022-10-10 03:47 UTC
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/3037552/194796746-f4670d8e-f3de-4fe4-9250-1ea9af72a4d6.png">

**Comment by noah-schechter** [comment] 2022-10-19 19:04
Closing this as a duplicate of #340.

**Closed by noah-schechter** 2022-10-19 19:04 UTC

**Comment by milesmcc** [comment] 2022-10-19 20:26
Lol how many times can I notice this and not realize it's a dupe
